### ISSUE TITLE
Peut-on ajouter des noms ?

### ISSUE THREAD

**Issue by fpom** [coti/interactions#1]
N'importe qui, juste des informaticiens, ou... quelle est la règle ?

**Comment by coti** [comment]
Il y a Claire, on peut mettre des non-informaticiens je pense

**Comment by fpom** [comment]
Permanents, doctorants, OSEF, ... ?

**Comment by lauregonnord** [comment]
OSEF ! Pas de ségrégation ici !

**Comment by coti** [comment]
Oui on est super open, on accepte même les doctorants ! :D

**Comment by fpom** [comment]
OK, ça roule.
